import type { Exhibit } from '../../lib/exhibit';
export const gears: Exhibit = {
 id:'gears',number:'02',scene:'gears',title:'Gear ratios',subtitle:'A little slower. A lot stronger. There’s a trade hiding in these teeth.',question:'How can gears make something stronger but slower?',duration:'2 min',author:'OpenEngineering contributors',period:1080,speed:60,
 controls:[{id:'ratio',label:'Driver → driven teeth',kind:'select',default:2,options:[{label:'16 → 16 · equal',value:1},{label:'16 → 32 · reduction',value:2},{label:'16 → 48 · more reduction',value:3},{label:'32 → 16 · speed increase',value:.5}]},{id:'speed',label:'Playback speed',kind:'select',default:1,options:[{label:'Slow · ½×',value:.5},{label:'Normal · 1×',value:1}]}],
 parts:[{id:'driver',name:'Driver gear',description:'The orange input receives rotation. Its teeth push against the blue gear’s teeth.'},{id:'driven',name:'Driven gear',description:'The blue output turns the opposite way. Its tooth count determines how far it turns for each input revolution.'}],
 steps:[
 {id:'pass-it-on',label:'01 / PASS THE MOTION',title:'One tooth pushes the next.',body:'Turn the orange gear. Where the teeth meet, it pushes the blue gear the other way. Two external gears always rotate in opposite directions.',why:'The teeth keep their motions linked. At the contact, both gears must move the same distance along their pitch circles.',experiment:'Pause and scrub backward. Both gears reverse, but they still turn in opposite directions.',deeper:'These are ideal external spur gears. The displayed tooth outlines are schematic, not manufacturing-ready involute profiles. Pitch radii grow in proportion to tooth count.',parts:['driver','driven'],controls:['ratio'],phase:60,camera:[1,3.5,10],defaults:{ratio:1}},
 {id:'count-the-teeth',label:'02 / COUNT THE TEETH',title:'Twice the teeth. Half the turns.',body:'Give the blue gear 32 teeth and the orange gear 16. The input must turn twice to move all 32 teeth of the output past the contact.',why:'The bigger output turns more slowly. The same input motion is spread over more teeth.',experiment:'Choose 16 → 32. Scrub from 0° to 360°: the orange gear makes a full turn and the blue gear makes half a turn.',deeper:'Output angular speed / input angular speed = −driver teeth / driven teeth. The minus sign indicates opposite direction. The white markers help you compare rotation.',parts:['driven'],controls:['ratio'],phase:180,camera:[1,3,11],defaults:{ratio:2}},
 {id:'trade-speed',label:'03 / A FAIR TRADE',title:'Slower can mean stronger.',body:'At the same contact force, a bigger output gear has a longer lever arm. It delivers more turning effect—torque—while rotating more slowly.',why:'In an ideal gear pair, power stays the same. Doubling torque halves speed. Real gears lose some energy to friction and other effects.',experiment:'Switch from 16 → 32 to 16 → 48. Compare the ideal torque and speed ratios below the model.',deeper:'Torque ratio = driven teeth / driver teeth when losses are ignored. Power = torque × angular speed. The ratios are calculated; neither an applied load nor real torque in newton-metres is simulated.',parts:['driver','driven'],controls:['ratio'],phase:120,camera:[1,3.5,12]},
 {id:'reverse-the-trade',label:'04 / TRY THE OPPOSITE',title:'Want speed? Give up torque.',body:'Make the orange driver larger than the blue output. Now one input turn pushes enough teeth to spin the output more than once.',why:'Gearboxes let a machine choose a useful compromise between speed and turning force. There is no free gain in both.',experiment:'Choose 32 → 16. Can you predict the speed ratio before looking? Then try another pair.',deeper:'A compound gearbox can multiply several ratios, and an idler can change direction without changing the overall magnitude for a simple chain. Those systems are beyond this two-gear exhibit.',parts:['driver','driven'],controls:['ratio','speed'],phase:120,camera:[1,3.5,10],defaults:{ratio:.5}}
 ],sources:[{title:'KHK — Gear technical reference',url:'https://khkgears.net/gear-knowledge/gear-technical-reference/calculation-gear-dimensions/'},{title:'Bartosz Ciechanowski — Gears',url:'https://ciechanow.ski/gears/'}],limitations:'Ideal external gears with schematic teeth and no backlash, friction, material deformation or load. Torque is an ideal ratio, not a simulated force.',assetCredits:'Original procedural gears and educational text. No imported assets.'
};
